"""add post title

Revision ID: 9726daf19d1b
Revises: 5d8371896502
Create Date: 2019-07-10 19:17:53.985479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9726daf19d1b'
down_revision = '5d8371896502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
